### ISSUE TITLE
remove module version number from `<scoped-name>`

### ISSUE THREAD

**Issue by majewsky** [vt6/vt6#18]
We include the module version number in message types, property names and capability names, e.g. `core1.set` rather than `core.set`. I've been thinking, and I don't see any actual reason for that. What it might do, however, is make backwards-compatible implementations harder: When a client says `(want core1 core2)`, it always has to keep track of which version was agreed to by the server, even if it only uses features which remain identical across major versions, so that it can form the correct message types. Also, it may mean that a backwards-compatible client needs more roundtrips than necessary to negotiate capabilities, e.g.

```
(want core1 core2) ---> wait for reply -+-> (want core1.some-capability) ---> wait for reply
                                        |
                                        `-> (want core2.some-capability) ---> wait for reply
```

instead of:

```
(want core1 core2 core.some-capability) ---> wait for reply
```

I suggest that we remove the module version number from `<scoped-name>`, e.g. `core1.set` becomes `core.set`. I'm putting this as a question issue rather than a PR since this leads to changes in every module, and I want to make sure we agree on this before I actually invest the time to make the edits.

**Comment by laerling** [comment]
Physically discussed. Fair enough.
Little note: The additional roundtrip mentioned is not necessary: `(want core1 core2 core1.some-capability core2.some-capability) ---> wait for reply`
