### ISSUE TITLE
clarify terms: "module", "module specification", "module version"

### ISSUE THREAD

**Issue by majewsky** [vt6/vt6#24]
[vt6/core1.0](https://github.com/vt6/vt6/blob/2df25bf42f32fbc1a255eb60ea823611c76c03b8/spec/core/1.0.md) currently uses the terms "module", "module specification" and "module version" in contradictory ways. My favorite is the first sentence in chapter 1:

> The VT6 protocol is divided into modules

versus the first sentence in chapter 3:

> The VT6 protocol specification is divided into modules [...]

We should clarify the definitions of terms surrounding the concept of modules. This does not block implementation efforts, but should be addressed before releasing core1.0.

**Comment by laerling** [comment]
This seems rather trivial to me.
"module" means the concept and its implementation, "module specification" means the description of what the module entails/does/offers and what it's good for etc., "module version" means a number that is associated with a specific derivate of the module (according to [semantic versioning](https://semver.org/), please).

The only thing left to do is to comb through all documentation and adjust the wording, if need be.

**Comment by majewsky** [comment]
- *module:* a versioned namespace for message types, properties, capabilities
- *module version:* synonymous to *module specification* because of an isomorphic relationship between both
